export const DEVICES = [
  {
    slug: "ip16",
    name: "iphone 16",
    viewport: { width: 393, height: 852 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ip16.png",
    screenPct: {
      top: 2.2,
      right: 5,
      bottom: 2.2,
      left: 5,
      radius: 13.0,
      scale: 0.8,
    },
  },
  {
    slug: "mb-air",
    name: "MacBook Air",
    viewport: { width: 1280, height: 750 },
    ua: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    platform: "macOS",
    mockup: "assets/devices/macbook-air.png",
    screenPct: {
      top: 5.0,
      right: 10,
      bottom: 5.0,
      left: 10,
      radius: 1.0,
      scale: 0.8,
    },
  },
  {
    slug: "apple-imac",
    name: `Apple iMac 24"`,
    viewport: { width: 1280, height: 1152 },
    ua: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    platform: "macOS",
    mockup: "assets/devices/apple-imac.png",
    screenPct: {
      top: 2.8,
      right: 1,
      bottom: 35,
      left: 1,
      radius: 0,
      scale: 0.6,
    },
  },
  {
    slug: "applewatch",
    name: "Apple Watch Series 6",
    viewport: { width: 162, height: 197 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/applewatch.png",
    screenPct: { top: 22, right: 10, bottom: 22, left: 10, radius: 3, scale: 1.2 },
  },
  {
    slug: "dell14",
    name: "Dell Latitude",
    viewport: { width: 1440, height: 1000 },
    ua: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    platform: "macOS",
    mockup: "assets/devices/dell14.png",
    screenPct: {
      top: 6.5,
      right: 9,
      bottom: 25,
      left: 9,
      radius: 0,
      scale: 0.65,
    },
  },
  {
    slug: "gpixel5",
    name: "Google Pixel 5",
    viewport: { width: 393, height: 851 },
    ua: "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    platform: "Android",
    mockup: "assets/devices/gpixel5.png",
    screenPct: {
      top: 2,
      right: 4.5,
      bottom: 1,
      left: 4.5,
      radius: 3,
      scale: 0.85,
    },
    statusBarPadding: [0, 15, 0, 45],
  },
  {
    slug: "gpixel6",
    name: "Google Pixel 6 PRO",
    viewport: { width: 360, height: 780 },
    ua: "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    platform: "Android",
    mockup: "assets/devices/gpixel6.png",
    screenPct: {
      top: 2,
      right: 0,
      bottom: 1,
      left: 0,
      radius: 3,
      scale: 0.85,
    },
  },
  {
    slug: "gpixel8",
    name: "Google pixel 8",
    viewport: { width: 412, height: 916 },
    ua: "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    platform: "Android",
    mockup: "assets/devices/gpixel8.png",
    screenPct: {
      top: 2,
      right: 2,
      bottom: 1,
      left: 2,
      radius: 3,
      scale: 0.7,
    },
    statusBarPadding: [0, 25, 0, 25],
  },
  {
    slug: "hp30",
    name: "Huawei P30 PRO",
    viewport: { width: 360, height: 780 },
    ua: "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    platform: "Android",
    mockup: "assets/devices/hp30.png",
    screenPct: {
      top: 2,
      right: 2,
      bottom: 1,
      left: 2,
      radius: 3,
      scale: 0.7,
    },
  },
  {
    slug: "ip11",
    name: "Iphone 11",
    viewport: { width: 414, height: 896 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ip11.png",
    screenPct: { top: 4, right: 7, bottom: 3, left: 7, radius: 3, scale: 0.8 },
  },
  {
    slug: "ip11pro",
    name: "Iphone 11 Pro",
    viewport: { width: 375, height: 812 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ip11pro.png",
    screenPct: { top: 3, right: 7, bottom: 3, left: 7, radius: 3, scale: 0.8 },
  },
  {
    slug: "ip11promax",
    name: "Iphone 11 pro max",
    viewport: { width: 414, height: 896 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ip11promax.png",
    screenPct: { top: 2, right: 6, bottom: 2, left: 6, radius: 3, scale: 0.8 },
  },
  {
    slug: "ip12",
    name: "Iphone 12",
    viewport: { width: 390, height: 844 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ip12.png",
    screenPct: { top: 2, right: 5, bottom: 2, left: 5, radius: 3, scale: 0.8 },
  },
  {
    slug: "ip12max",
    name: "Iphone 12 max",
    viewport: { width: 390, height: 844 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ip12max.png",
    screenPct: { top: 2, right: 5, bottom: 2, left: 5, radius: 3, scale: 0.8 },
  },
  {
    slug: "ip12mini",
    name: "Iphone 12 mini",
    viewport: { width: 360, height: 780 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ip12mini.png",
    screenPct: { top: 2, right: 5, bottom: 2, left: 5, radius: 3, scale: 0.85 },
  },
  {
    slug: "ip12promax",
    name: "Iphone 12 pro max",
    viewport: { width: 428, height: 926 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ip12promax.png",
    screenPct: { top: 2, right: 5, bottom: 2, left: 5, radius: 3, scale: 0.8 },
  },
  {
    slug: "ip13",
    name: "Iphone 13",
    viewport: { width: 390, height: 844 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ip13.png",
    screenPct: { top: 2, right: 5, bottom: 2, left: 5, radius: 3, scale: 0.8 },
  },
  {
    slug: "ip13mini",
    name: "Iphone 13 mini",
    viewport: { width: 375, height: 812 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ip13mini.png",
    screenPct: { top: 2, right: 5, bottom: 2, left: 5, radius: 3, scale: 0.85 },
  },
  {
    slug: "ip13pro",
    name: "Iphone 13 pro",
    viewport: { width: 390, height: 844 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ip13pro.png",
    screenPct: { top: 2, right: 4, bottom: 2, left: 4, radius: 3, scale: 0.8 },
  },
  {
    slug: "ip13promax",
    name: "Iphone 13 pro max",
    viewport: { width: 428, height: 926 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ip13promax.png",
    screenPct: { top: 2, right: 5, bottom: 2, left: 5, radius: 3, scale: 0.8 },
  },
  {
    slug: "ip14",
    name: "Iphone 14",
    viewport: { width: 390, height: 844 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ip14.png",
    screenPct: { top: 2, right: 4, bottom: 2, left: 4, radius: 3, scale: 0.8 },
  },
  {
    slug: "ip14max",
    name: "Iphone 14 max",
    viewport: { width: 428, height: 926 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ip14max.png",
    screenPct: {
      top: 2,
      right: 4.8,
      bottom: 2,
      left: 5,
      radius: 3,
      scale: 0.8,
    },
  },
  {
    slug: "ip14pro",
    name: "Iphone 14 pro",
    viewport: { width: 390, height: 844 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ip14pro.png",
    screenPct: { top: 2, right: 5, bottom: 2, left: 5, radius: 3, scale: 0.8 },
  },
  {
    slug: "ip14promax",
    name: "Iphone 14 pro max",
    viewport: { width: 428, height: 928 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ip14promax.png",
    screenPct: {
      top: 2,
      right: 4.9,
      bottom: 2,
      left: 5,
      radius: 3,
      scale: 0.8,
    },
  },
  {
    slug: "ip15",
    name: "Iphone 15",
    viewport: { width: 393, height: 852 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ip15.png",
    screenPct: {
      top: 1.8,
      right: 4.5,
      bottom: 1.8,
      left: 4.5,
      radius: 3,
      scale: 0.8,
    },
  },
  {
    slug: "ip15plus",
    name: "Iphone 15 plus",
    viewport: { width: 430, height: 932 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ip15plus.png",
    screenPct: {
      top: 1.8,
      right: 4.5,
      bottom: 1.8,
      left: 4.5,
      radius: 3,
      scale: 0.8,
    },
  },
  {
    slug: "ip15pro",
    name: "Iphone 15 pro",
    viewport: { width: 393, height: 852 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ip15pro.png",
    screenPct: {
      top: 1.8,
      right: 4.5,
      bottom: 1.8,
      left: 4.5,
      radius: 4.3,
      scale: 0.8,
    },
  },
  {
    slug: "ip15promax",
    name: "Iphone 15 pro max",
    viewport: { width: 430, height: 932 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ip15promax.png",
    screenPct: {
      top: 1.5,
      right: 4,
      bottom: 1.5,
      left: 4,
      radius: 5,
      scale: 0.8,
    },
  },
  {
    slug: "ip16plus",
    name: "Iphone 16 plus",
    viewport: { width: 430, height: 932 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ip16plus.png",
    screenPct: {
      top: 2,
      right: 4,
      bottom: 2,
      left: 4,
      radius: 5,
      scale: 0.8,
    },
  },
  {
    slug: "ip16promax",
    name: "Iphone 16 pro max",
    viewport: { width: 440, height: 956 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ip16promax.png",
    screenPct: {
      top: 1.8,
      right: 4,
      bottom: 1.8,
      left: 4,
      radius: 6.5,
      scale: 0.8,
    },
  },
  {
    slug: "ip5",
    name: "Iphone 5",
    viewport: { width: 320, height: 568 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ip5.png",
    screenPct: { top: 14, right: 5, bottom: 14, left: 5, radius: 3, scale: 1 },
  },
  {
    slug: "ipad-air",
    name: "ipad air",
    viewport: { width: 820, height: 1180 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ipad-air.png",
    screenPct: { top: 4, right: 5, bottom: 4, left: 5, radius: 3 },
  },
  {
    slug: "ipad-mini",
    name: "ipad mini",
    viewport: { width: 768, height: 1024 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ipad-mini.png",
    screenPct: { top: 10, right: 5, bottom: 10, left: 5, radius: 3 },
  },
  {
    slug: "ipad-pro",
    name: "ipad pro",
    viewport: { width: 834, height: 1194 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ipad-pro.png",
    screenPct: { top: 3.5, right: 4.8, bottom: 3.5, left: 4.8, radius: 3 },
  },
  {
    slug: "ipse",
    name: "Iphone SE",
    viewport: { width: 320, height: 586 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ipse.png",
    screenPct: { top: 12, right: 5, bottom: 12, left: 5, radius: 3, scale: 1 },
  },
  {
    slug: "ipx",
    name: "Iphone X",
    viewport: { width: 375, height: 812 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ipx.png",
    screenPct: {
      top: 2,
      right: 4.5,
      bottom: 2,
      left: 4.5,
      radius: 4.3,
      scale: 0.8,
    },
  },
  {
    slug: "ipxr",
    name: "Iphone XR",
    viewport: { width: 414, height: 896 },
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    platform: "iOS",
    mockup: "assets/devices/ipxr.png",
    screenPct: {
      top: 3.5,
      right: 5.5,
      bottom: 2,
      left: 5.5,
      radius: 4.3,
      scale: 0.8,
    },
  },
  {
    slug: "macbookpro",
    name: "Macbook Pro 2021",
    viewport: { width: 1528, height: 1055 },
    ua: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    platform: "macOS",
    mockup: "assets/devices/macbookpro.png",
    screenPct: {
      top: 3.5,
      right: 8,
      bottom: 8,
      left: 8,
      radius: 1,
      scale: 0.6,
    },
  },
  {
    slug: "microsoftsurfaceduo",
    name: "Microsoft Surface Duo",
    viewport: { width: 1114, height: 705 },
    ua: "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    platform: "Android",
    mockup: "assets/devices/microsoftsurfaceduo.png",
    screenPct: { top: 9, right: 5, bottom: 9, left: 5, radius: 3 },
  },
  {
    slug: "nord2",
    name: "Oneplus Nord 2",
    viewport: { width: 412, height: 915 },
    ua: "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    platform: "Android",
    mockup: "assets/devices/nord2.png",
    screenPct: {
      top: 2,
      right: 2,
      bottom: 3,
      left: 2,
      radius: 3,
      scale: 0.7,
    },
    statusBarPadding: [0, 25, 0, 60],
  },
  {
    slug: "ofindx3",
    name: "OPPO Find X3",
    viewport: { width: 360, height: 804 },
    ua: "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    platform: "Android",
    mockup: "assets/devices/ofindx3.png",
    screenPct: {
      top: 2,
      right: 2,
      bottom: 3,
      left: 2,
      radius: 3,
    },
    statusBarPadding: [0, 25, 0, 60],
  },
  {
    slug: "sgalaxya12",
    name: "Samsung Galaxy A12",
    viewport: { width: 360, height: 800 },
    ua: "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    platform: "Android",
    mockup: "assets/devices/sgalaxya12.png",
    screenPct: {
      top: 2,
      right: 2,
      bottom: 3,
      left: 2,
      radius: 3,
      scale: 0.7,
    },
  },
  {
    slug: "sgalaxyfold",
    name: "Samsung Galaxy Fold",
    viewport: { width: 844, height: 1104 },
    ua: "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    platform: "Android",
    mockup: "assets/devices/sgalaxyfold.png",
    screenPct: {
      top: 1.8,
      right: 2,
      bottom: 1.8,
      left: 2,
      radius: 3,
      scale: 0.6,
    },
  },
  {
    slug: "sgalaxynote20ultra",
    name: "Samsung Galaxy Note 20 Ultra",
    viewport: { width: 360, height: 800 },
    ua: "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    platform: "special",
    mockup: "assets/devices/sgalaxynote20ultra.png",
    screenPct: {
      top: 0,
      right: 0.5,
      bottom: 2,
      left: 0,
      radius: 3,
      scale: 0.8,
    },
  },
  {
    slug: "sgalaxys12ultra",
    name: "Samsung Galaxy S12 Ultra",
    viewport: { width: 412, height: 883 },
    ua: "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    platform: "Android",
    mockup: "assets/devices/sgalaxys12ultra.png",
    screenPct: {
      top: 1.4,
      right: 2,
      bottom: 2,
      left: 2,
      radius: 3,
      scale: 0.7,
    },
  },
  {
    slug: "sgalaxys20",
    name: "Samsung Galaxy S20",
    viewport: { width: 360, height: 800 },
    ua: "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    platform: "Android",
    mockup: "assets/devices/sgalaxys20.png",
    screenPct: { top: 1, right: 4, bottom: 1, left: 4, radius: 3 },
  },
  {
    slug: "sgalaxys22",
    name: "Samsung Galaxy S22",
    viewport: { width: 360, height: 780 },
    ua: "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    platform: "Android",
    mockup: "assets/devices/sgalaxys22.png",
    screenPct: { top: 1, right: 4, bottom: 1, left: 4, radius: 3 },
  },
  {
    slug: "sgalaxys22plus",
    name: "Samsung Galaxy S22 Plus",
    viewport: { width: 360, height: 780 },
    ua: "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    platform: "Android",
    mockup: "assets/devices/sgalaxys22plus.png",
    screenPct: { top: 1, right: 4, bottom: 1, left: 3.8, radius: 3 },
  },
  {
    slug: "sgalaxys22ultra",
    name: "Samsung Galaxy S22 Ultra",
    viewport: { width: 360, height: 772 },
    ua: "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    platform: "Android",
    mockup: "assets/devices/sgalaxys22ultra.png",
    screenPct: { top: 0, right: 1, bottom: 0, left: 1, radius: 3 },
  },
  {
    slug: "sgalaxys24",
    name: "Samsung Galaxy S24",
    viewport: { width: 360, height: 780 },
    ua: "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    platform: "Android",
    mockup: "assets/devices/sgalaxys24.png",
    screenPct: { top: 1, right: 4, bottom: 1, left: 3.3, radius: 3 },
  },
  {
    slug: "sgalaxys24ultra",
    name: "Samsung Galaxy S24 Ultra",
    viewport: { width: 384, height: 832 },
    ua: "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    platform: "Android",
    mockup: "assets/devices/sgalaxys24ultra.png",
    screenPct: { top: 1, right: 4.5, bottom: 1, left: 4, radius: 3 },
  },
  {
    slug: "sgalaxytabs7",
    name: "Samsung Galaxy Tab S7",
    viewport: { width: 800, height: 1280 },
    ua: "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    platform: "Android",
    mockup: "assets/devices/sgalaxytabs7.png",
    screenPct: { top: 3, right: 5, bottom: 3, left: 5, radius: 3 },
  },
  {
    slug: "sgalaxyzflip",
    name: "Samsung Galaxy Z Flip",
    viewport: { width: 360, height: 880 },
    ua: "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    platform: "Android",
    mockup: "assets/devices/sgalaxyzflip.png",
    screenPct: { top: 2, right: 5, bottom: 2, left: 5, radius: 3 },
  },
  {
    slug: "ssmarttv",
    name: "Samsung Smart TV",
    viewport: { width: 1920, height: 1080 },
    ua: "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    platform: "Android",
    mockup: "assets/devices/ssmarttv.png",
    screenPct: { top: 0.5, right: 0.5, bottom: 9, left: 0.5, radius: 0 },
  },
  {
    slug: "undefined-medium_upscaled",
    name: "Non-Branded Phone",
    viewport: { width: 360, height: 800 },
    ua: "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    platform: "Android",
    mockup: "assets/devices/undefined-medium_upscaled.png",
    screenPct: { top: 5, right: 5, bottom: 5, left: 5, radius: 3 },
  },
  {
    slug: "x12",
    name: "Xiaomi 12",
    viewport: { width: 360, height: 800 },
    ua: "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    platform: "Android",
    mockup: "assets/devices/x12.png",
    screenPct: { top: 1.5, right: 2, bottom: 2, left: 2, radius: 3 },
  },
  {
    slug: "xm11i",
    name: "Xiaomi 11i",
    viewport: { width: 360, height: 800 },
    ua: "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    platform: "Android",
    mockup: "assets/devices/xm11i.png",
    screenPct: { top: 2, right: 2, bottom: 2, left: 2, radius: 3 },
  },
];

export const getDeviceBySlug = (slug) => {
  return DEVICES.find((device) => device.slug === slug) || DEVICES[0];
};

export const getDefaultDevice = () => DEVICES[0];

// Ensure every device has a configurable status bar padding value
// Use array format [top, right, bottom, left] in pixels for fine control
DEVICES.forEach((device) => {
  if (device.statusBarPadding == null) {
    device.statusBarPadding = [0, 15, 0, 15];
  }
  if (typeof device.statusBarPadding === "number") {
    const v = device.statusBarPadding;
    device.statusBarPadding = [v, v, v, v];
  }
  if (Array.isArray(device.statusBarPadding)) {
    const a = device.statusBarPadding;
    device.statusBarPadding = [a[0] || 0, a[1] || 0, a[2] || 0, a[3] || 0];
  }
});